# Generated by Django 4.1.4 on 2022-12-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student_c_password_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
